In [1]:
import os

# Install git if not already installed
!apt-get install -y git

# Clone the repository
!git clone https://github.com/Elite-AI-Club/AI-Driven-Innovation-Electronics.git

# Change working directory to the repository
%cd AI-Driven-Innovation-Electronics/7_PCB_Fault_Detection

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Cloning into 'AI-Driven-Innovation-Electronics'...
remote: Enumerating objects: 1319, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 1319 (delta 29), reused 102 (delta 29), pack-reused 1217 (from 1)
Receiving objects: 100% (1319/1319), 109.39 MiB | 26.59 MiB/s, done.
Resolving deltas: 100% (33/33), done.
Updating files: 100% (1339/1339), done.
/content/AI-Driven-Innovation-Electronics/7_PCB_Fault_Detection


In [2]:
pwd

'/content/AI-Driven-Innovation-Electronics/7_PCB_Fault_Detection'

In [3]:
import os
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array

In [4]:
def get_model():
    global model
    model = load_model('model.h5')
    print("Model loaded!")

In [5]:
get_model()

Model loaded!


In [6]:
def load_image(img_path):

    img = image.load_img(img_path, target_size=(224, 224))
    img_tensor = image.img_to_array(img)                    # (height, width, channels)
    img_tensor = np.expand_dims(img_tensor, axis=0)         # (1, height, width, channels), add a dimension because the model expects this shape: (batch_size, height, width, channels)
    img_tensor /= 255.                                      # imshow expects values in the range [0, 1]

    return img_tensor

In [7]:
def prediction(img_path):
    new_image = load_image(img_path)

    pred = model.predict(new_image)

    print(pred)

    labels=np.array(pred)
    labels[labels>=0.6]=1
    labels[labels<0.6]=0

    print(labels)
    final=np.array(labels)

    if final[0][0]==1:
        return "Bad"
    else:
        return "Good"

In [9]:
prediction(r'dataset/test/test5/bad (75)k.jpeg')

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[0.9875107  0.01248937]]
[[1. 0.]]


'Bad'

In [11]:
print(prediction(r'dataset/test/test5/good (361)k.jpeg'))                                #significance of r"

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
[[0.0125276 0.9874724]]
[[0. 1.]]
Good


In [12]:
product = prediction(r'dataset/test/test5/bad (25)k.jpeg')                                                                        #it will accept image directly if both .ipynb and image lie on same place

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
[[9.9993622e-01 6.3810214e-05]]
[[1. 0.]]


In [13]:
product

'Bad'